### ISSUE TITLE
Crash on game launch with Oh The Biomes We've Gone

### ISSUE THREAD

**Issue by ahowell610** [SagaDeoMissTeam/SDMShop#2]
Here is what the log says:

Exception in thread "main" java.lang.module.ResolutionException: Modules sdm_core and corgilib export package imgui.extension.nodeditor.flag to module apoli

I tried disabling Origins (which is where apoli is from) and that didnt work. When I disable SDM Shop and SDM Core the game boots and runs fine.

**Comment by SagaDeoMissTeam** [comment]
Send latest.log

**Comment by SagaDeoMissTeam** [comment]
My library is not compatible with corgilib. I think even if I really want to, I won't be able to make compatibility due to the fact that it has the same Framework as mine
